/*
Copyright [2023] [Amrudesh Balakrishnan]

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package apk

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"morf/models"
)

// ---- pubspec.lock tests ----

const pubspecLockFixture = `# Generated by pub - do not edit!
packages:
  async:
    dependency: transitive
    description:
      name: async
      sha256: "947bfcf187f74dbc5e146c9eb9c0f10c9f8b1463d4beccb500a2dba226c7f99e"
      url: "https://pub.dev"
    source: hosted
    version: "2.11.0"
  characters:
    dependency: transitive
    description:
      name: characters
      sha256: "04a925763edad35eb6fb96cc82ac14b63acb1aefa8f06e22cd0bee79f1b5bc63"
      url: "https://pub.dev"
    source: hosted
    version: "1.3.0"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  http:
    dependency: "direct main"
    description:
      name: http
      sha256: "761a297c042deedc1ffbb156d6e2af13886bb305c2a343a4d972504cd67dd938"
      url: "https://pub.dev"
    source: hosted
    version: "1.2.2"
  path:
    dependency: transitive
    description:
      name: path
      sha256: "087ce49c3f0dc39180befefc60fdb4acd8f8620e5682fe2476afd0b3688bb4af"
      url: "https://pub.dev"
    source: hosted
    version: "1.9.0"
  provider:
    dependency: "direct main"
    description:
      name: provider
      sha256: "9a96a0a19b594dbc5bf0f1f27d2bc67d5f95957359b461671d84b22e60849d1a"
      url: "https://pub.dev"
    source: hosted
    version: "6.1.2"
sdks:
  dart: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"
`

func TestParsePubspecLock_ParsesVersions(t *testing.T) {
	got := ParsePubspecLock([]byte(pubspecLockFixture))

	cases := map[string]string{
		"async":      "2.11.0",
		"characters": "1.3.0",
		"http":       "1.2.2",
		"path":       "1.9.0",
		"provider":   "6.1.2",
		// flutter is sdk-sourced with version "0.0.0" — it IS parsed.
		"flutter": "0.0.0",
	}
	for name, want := range cases {
		if got[name] != want {
			t.Errorf("pubspec.lock: %q version = %q, want %q", name, got[name], want)
		}
	}
}

func TestParsePubspecLock_Empty(t *testing.T) {
	got := ParsePubspecLock([]byte(""))
	if len(got) != 0 {
		t.Errorf("empty input: expected no packages, got %v", got)
	}
}

func TestParsePubspecLock_MalformedSkipped(t *testing.T) {
	// Malformed YAML should not panic; unknown structure yields empty map.
	got := ParsePubspecLock([]byte("this: is: not: valid: pubspec"))
	_ = got // no assertion: just must not panic
}

// ---- package-lock.json tests ----

const packageLockV2Fixture = `{
  "name": "myapp",
  "version": "1.0.0",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "name": "myapp",
      "version": "1.0.0"
    },
    "node_modules/react": {
      "version": "18.2.0",
      "resolved": "https://registry.npmjs.org/react/-/react-18.2.0.tgz",
      "integrity": "sha512-dummy"
    },
    "node_modules/react-native": {
      "version": "0.73.6",
      "resolved": "https://registry.npmjs.org/react-native/-/react-native-0.73.6.tgz"
    },
    "node_modules/@react-navigation/native": {
      "version": "6.1.9",
      "resolved": "https://registry.npmjs.org/@react-navigation/native/-/native-6.1.9.tgz"
    },
    "node_modules/react/node_modules/scheduler": {
      "version": "0.23.0",
      "resolved": "https://registry.npmjs.org/scheduler/-/scheduler-0.23.0.tgz"
    }
  }
}`

func TestParsePackageLockJSON_V2(t *testing.T) {
	got := ParsePackageLockJSON([]byte(packageLockV2Fixture))

	// Root package (key "") must be skipped.
	if _, ok := got[""]; ok {
		t.Error("root package \"\" should be skipped")
	}

	cases := map[string]string{
		"react":                    "18.2.0",
		"react-native":             "0.73.6",
		"@react-navigation/native": "6.1.9",
		// Nested path "react/node_modules/scheduler" → "scheduler"
		"scheduler": "0.23.0",
	}
	for name, want := range cases {
		if got[name] != want {
			t.Errorf("package-lock.json: %q version = %q, want %q", name, got[name], want)
		}
	}
}

func TestParsePackageLockJSON_InvalidJSON(t *testing.T) {
	got := ParsePackageLockJSON([]byte("{invalid"))
	if len(got) != 0 {
		t.Errorf("invalid JSON: expected empty map, got %v", got)
	}
}

func TestParsePackageLockJSON_NoPackagesKey(t *testing.T) {
	got := ParsePackageLockJSON([]byte(`{"name":"x","version":"1"}`))
	if len(got) != 0 {
		t.Errorf("no packages key: expected empty map, got %v", got)
	}
}

// ---- yarn.lock tests ----

const yarnLockV1Fixture = `# yarn lockfile v1


"@react-native-community/netinfo@^11.0.0":
  version "11.3.1"
  resolved "https://registry.yarnpkg.com/@react-native-community/netinfo/-/netinfo-11.3.1.tgz"
  integrity sha512-dummy

"react@^18.0.0", "react@^18.2.0":
  version "18.2.0"
  resolved "https://registry.yarnpkg.com/react/-/react-18.2.0.tgz"

react-native@0.73.6:
  version "0.73.6"
  resolved "https://registry.yarnpkg.com/react-native/-/react-native-0.73.6.tgz"

lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
`

func TestParseYarnLock_V1(t *testing.T) {
	got := ParseYarnLock([]byte(yarnLockV1Fixture))

	cases := map[string]string{
		"@react-native-community/netinfo": "11.3.1",
		"react":                           "18.2.0",
		"react-native":                    "0.73.6",
		"lodash":                          "4.17.21",
	}
	for name, want := range cases {
		if got[name] != want {
			t.Errorf("yarn.lock: %q version = %q, want %q", name, got[name], want)
		}
	}
}

// TestParseYarnLock_BerrySkipped asserts that a yarn berry (__metadata:) file
// is silently skipped (returns empty map) rather than misparsed.
func TestParseYarnLock_BerrySkipped(t *testing.T) {
	berryFixture := `__metadata:
  version: 6
  cacheKey: 8

"react@npm:^18.0.0":
  version: 18.2.0
`
	got := ParseYarnLock([]byte(berryFixture))
	if len(got) != 0 {
		t.Errorf("yarn berry: expected empty map (should be skipped), got %v", got)
	}
}

func TestParseYarnLock_Empty(t *testing.T) {
	got := ParseYarnLock([]byte(""))
	if len(got) != 0 {
		t.Errorf("empty input: expected no packages, got %v", got)
	}
}

// ---- Enrichment integration tests ----

// buildTestComponents builds a slice with the given names and no versions, to
// simulate components detected by binary/runtime analysis before lockfile
// enrichment.
func buildTestComponents(names ...string) []models.SBOMComponent {
	out := make([]models.SBOMComponent, 0, len(names))
	for _, name := range names {
		out = append(out, models.NewRuntimeComponent(name, nil))
	}
	return out
}

// TestEnrichFromAndroidLockfiles_PubspecLock verifies that a component matching
// a pubspec.lock entry gets its Version set and purl upgraded to pkg:pub.
func TestEnrichFromAndroidLockfiles_PubspecLock(t *testing.T) {
	jc := jobCtxForDir(t, "enrich-pub")

	// Write a pubspec.lock into the workspace root.
	lockContent := `packages:
  http:
    dependency: "direct main"
    description:
      name: http
      url: "https://pub.dev"
    source: hosted
    version: "1.2.2"
  provider:
    dependency: "direct main"
    description:
      name: provider
      url: "https://pub.dev"
    source: hosted
    version: "6.1.2"
sdks:
  dart: ">=3.0.0 <4.0.0"
`
	if err := os.WriteFile(filepath.Join(jc.Workspace, "pubspec.lock"), []byte(lockContent), 0o600); err != nil {
		t.Fatalf("write pubspec.lock: %v", err)
	}

	// A Flutter runtime component was detected via binary analysis (no version).
	initial := []models.SBOMComponent{
		models.NewRuntimeComponent("Flutter", []string{"lib/arm64-v8a/libflutter.so"}),
	}

	enriched := EnrichFromAndroidLockfiles(jc, initial)

	// The Flutter runtime component should be unchanged (no flutter entry in our fixture).
	var flutter *models.SBOMComponent
	for i := range enriched {
		if enriched[i].Name == "Flutter" {
			flutter = &enriched[i]
		}
	}
	if flutter == nil {
		t.Fatal("Flutter component missing after enrichment")
	}
	if flutter.Version != "" {
		t.Errorf("Flutter.Version = %q, want empty (not in pubspec.lock)", flutter.Version)
	}

	// New components should have been added for http and provider.
	byName := indexByName(enriched)
	httpC, ok := byName["http"]
	if !ok {
		t.Fatal("http component missing; expected new component from pubspec.lock")
	}
	if httpC.Version != "1.2.2" {
		t.Errorf("http.Version = %q, want 1.2.2", httpC.Version)
	}
	if !strings.HasPrefix(httpC.Purl, "pkg:pub/http@") {
		t.Errorf("http.Purl = %q, want pkg:pub/http@...", httpC.Purl)
	}

	provC, ok := byName["provider"]
	if !ok {
		t.Fatal("provider component missing; expected new component from pubspec.lock")
	}
	if provC.Version != "6.1.2" {
		t.Errorf("provider.Version = %q, want 6.1.2", provC.Version)
	}
}

// TestEnrichFromAndroidLockfiles_PackageLock verifies package-lock.json enrichment.
func TestEnrichFromAndroidLockfiles_PackageLock(t *testing.T) {
	jc := jobCtxForDir(t, "enrich-npm")

	pkgLock := `{
  "lockfileVersion": 2,
  "packages": {
    "": { "name": "app" },
    "node_modules/react-native": { "version": "0.73.6" },
    "node_modules/lodash": { "version": "4.17.21" }
  }
}`
	if err := os.WriteFile(filepath.Join(jc.Workspace, "package-lock.json"), []byte(pkgLock), 0o600); err != nil {
		t.Fatalf("write package-lock.json: %v", err)
	}

	// Simulate a React Native runtime component detected from .so files.
	initial := []models.SBOMComponent{
		models.NewRuntimeComponent("React Native", []string{"lib/arm64-v8a/libhermes.so"}),
	}
	enriched := EnrichFromAndroidLockfiles(jc, initial)

	byName := indexByName(enriched)

	// react-native should be a new component.
	rnC, ok := byName["react-native"]
	if !ok {
		t.Fatal("react-native component missing from enriched list")
	}
	if rnC.Version != "0.73.6" {
		t.Errorf("react-native.Version = %q, want 0.73.6", rnC.Version)
	}
	if !strings.HasPrefix(rnC.Purl, "pkg:npm/react-native@") {
		t.Errorf("react-native.Purl = %q, want pkg:npm/react-native@...", rnC.Purl)
	}

	lodashC, ok := byName["lodash"]
	if !ok {
		t.Fatal("lodash component missing from enriched list")
	}
	if lodashC.Version != "4.17.21" {
		t.Errorf("lodash.Version = %q, want 4.17.21", lodashC.Version)
	}

	// The React Native runtime component should still be present.
	if _, ok := byName["React Native"]; !ok {
		t.Error("React Native runtime component should not have been removed")
	}
}

// TestEnrichFromAndroidLockfiles_NoLockfile asserts no-op when no lockfile exists.
func TestEnrichFromAndroidLockfiles_NoLockfile(t *testing.T) {
	jc := jobCtxForDir(t, "enrich-none")
	initial := []models.SBOMComponent{
		models.NewRuntimeComponent("Flutter", []string{"lib/arm64-v8a/libflutter.so"}),
	}
	enriched := EnrichFromAndroidLockfiles(jc, initial)
	if len(enriched) != len(initial) {
		t.Errorf("expected %d components (unchanged), got %d", len(initial), len(enriched))
	}
	if enriched[0].Version != "" {
		t.Errorf("version should be empty when no lockfile present, got %q", enriched[0].Version)
	}
}

// TestEnrichFromAndroidLockfiles_YarnLockFallback asserts that yarn.lock is
// used when package-lock.json is absent.
func TestEnrichFromAndroidLockfiles_YarnLockFallback(t *testing.T) {
	jc := jobCtxForDir(t, "enrich-yarn")

	yarnContent := `# yarn lockfile v1

react@^18.0.0:
  version "18.2.0"
  resolved "https://registry.yarnpkg.com/react/-/react-18.2.0.tgz"
`
	if err := os.WriteFile(filepath.Join(jc.Workspace, "yarn.lock"), []byte(yarnContent), 0o600); err != nil {
		t.Fatalf("write yarn.lock: %v", err)
	}

	initial := []models.SBOMComponent{}
	enriched := EnrichFromAndroidLockfiles(jc, initial)

	byName := indexByName(enriched)
	reactC, ok := byName["react"]
	if !ok {
		t.Fatal("react component missing; expected new component from yarn.lock")
	}
	if reactC.Version != "18.2.0" {
		t.Errorf("react.Version = %q, want 18.2.0", reactC.Version)
	}
	if !strings.HasPrefix(reactC.Purl, "pkg:npm/react@") {
		t.Errorf("react.Purl = %q, want pkg:npm/react@...", reactC.Purl)
	}
}

// TestEnrichFromAndroidLockfiles_PackageLockTakesPrecedence asserts that
// package-lock.json wins when both files are present.
func TestEnrichFromAndroidLockfiles_PackageLockTakesPrecedence(t *testing.T) {
	jc := jobCtxForDir(t, "enrich-both")

	pkgLock := `{"lockfileVersion":2,"packages":{"node_modules/react":{"version":"18.2.0"}}}`
	yarnLock := `# yarn lockfile v1
react@^18.0.0:
  version "17.0.0"
  resolved "https://x"
`
	if err := os.WriteFile(filepath.Join(jc.Workspace, "package-lock.json"), []byte(pkgLock), 0o600); err != nil {
		t.Fatalf("write package-lock.json: %v", err)
	}
	if err := os.WriteFile(filepath.Join(jc.Workspace, "yarn.lock"), []byte(yarnLock), 0o600); err != nil {
		t.Fatalf("write yarn.lock: %v", err)
	}

	enriched := EnrichFromAndroidLockfiles(jc, nil)
	byName := indexByName(enriched)
	if byName["react"].Version != "18.2.0" {
		t.Errorf("react.Version = %q, want 18.2.0 (package-lock.json should win)", byName["react"].Version)
	}
}

// indexByName builds a name→component index for assertions.
func indexByName(cs []models.SBOMComponent) map[string]models.SBOMComponent {
	m := make(map[string]models.SBOMComponent, len(cs))
	for _, c := range cs {
		m[c.Name] = c
	}
	return m
}
